language: node_js
node_js:
  - "4"
  - "5"
  - "6"
before_install:
  - npm config set progress false
script:
  - babel-node ./node_modules/.bin/isparta cover --report lcovonly _mocha -- $npm_package_config_mocha
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
